package dev.tuandoan.tasktracker.data.backup.dto

import dev.tuandoan.tasktracker.data.database.Subtask
import kotlinx.serialization.Serializable

/**
 * Data transfer object for serializing/deserializing a single subtask in backup files.
 * The `id` and `taskId` fields are informational only — on import, subtask ids are
 * regenerated by Room and `taskId` is re-wired from the enclosing parent task.
 */
@Serializable
data class SubtaskBackupDto(
    val id: Long = 0L,
    val title: String,
    val isCompleted: Boolean = false,
    val sortOrder: Int = 0,
    val createdAt: Long = 0L,
) {

    /**
     * Builds a [Subtask] domain entity. The parent [taskId] is supplied by the caller because
     * the enclosing [TaskBackupDto] owns the relationship.
     */
    fun toSubtask(taskId: Long): Subtask = Subtask(
        id = 0L,
        taskId = taskId,
        title = title,
        isCompleted = isCompleted,
        sortOrder = sortOrder,
        createdAt = if (createdAt <= 0L) System.currentTimeMillis() else createdAt,
    )

    companion object {
        fun fromSubtask(subtask: Subtask): SubtaskBackupDto = SubtaskBackupDto(
            id = subtask.id,
            title = subtask.title,
            isCompleted = subtask.isCompleted,
            sortOrder = subtask.sortOrder,
            createdAt = subtask.createdAt,
        )
    }
}
